version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:80"  # Map port 8000 on host to port 9000 in the container
    environment:
      - APP_URL=http://localhost:8001
      - VITE_LARAVEL_URL=http://localhost:8001
    # volumes:
    #   - ./public:/var/www/html/public  # Mount the public directory