version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:5173"  # Map port 3001 on host to port 80 in the container
    environment:
      - VITE_LARAVEL_URL=http://localhost:8001
